<?xml version="1.0" encoding="utf-8"?><!DOCTYPE context [<!ELEMENT context (device | context-attribute)*><!ELEMENT context-attribute EMPTY><!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*><!ELEMENT channel (scan-element?, attribute*)><!ELEMENT attribute EMPTY><!ELEMENT scan-element EMPTY><!ELEMENT debug-attribute EMPTY><!ELEMENT buffer-attribute EMPTY><!ATTLIST context name CDATA #REQUIRED version-major CDATA #REQUIRED version-minor CDATA #REQUIRED version-git CDATA #REQUIRED description CDATA #IMPLIED><!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED><!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED label CDATA #IMPLIED><!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED><!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED><!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED><!ATTLIST debug-attribute name CDATA #REQUIRED><!ATTLIST buffer-attribute name CDATA #REQUIRED>]><context name="xml" version-major="0" version-minor="25" version-git="b6028fd" description="Linux analog 6.1.54-v7l+ #78 SMP Tue Jan 16 15:52:19 EET 2024 armv7l" ><context-attribute name="hw_carrier" value="Raspberry Pi 4 Model B Rev 1.2" /><context-attribute name="dtoverlay" value="vc4-kms-v3d,adis16475" /><context-attribute name="hw_model" value="0x0001 on Raspberry Pi 4 Model B Rev 1.2" /><context-attribute name="local,kernel" value="6.1.54-v7l+" /><context-attribute name="uri" value="local:" /><device id="hwmon0" name="rpi_volt" ><channel id="in0" type="input" ><attribute name="lcrit_alarm" filename="in0_lcrit_alarm" /></channel></device><device id="iio:device0" name="adis16505-2" ><channel id="anglvel_x" type="input" ><scan-element index="0" format="be:S32/32&gt;&gt;0" scale="0.000000" /><attribute name="calibbias" filename="in_anglvel_x_calibbias" /><attribute name="raw" filename="in_anglvel_x_raw" /><attribute name="scale" filename="in_anglvel_scale" /></channel><channel id="anglvel_y" type="input" ><scan-element index="1" format="be:S32/32&gt;&gt;0" scale="0.000000" /><attribute name="calibbias" filename="in_anglvel_y_calibbias" /><attribute name="raw" filename="in_anglvel_y_raw" /><attribute name="scale" filename="in_anglvel_scale" /></channel><channel id="anglvel_z" type="input" ><scan-element index="2" format="be:S32/32&gt;&gt;0" scale="0.000000" /><attribute name="calibbias" filename="in_anglvel_z_calibbias" /><attribute name="raw" filename="in_anglvel_z_raw" /><attribute name="scale" filename="in_anglvel_scale" /></channel><channel id="accel_x" type="input" ><scan-element index="3" format="be:S32/32&gt;&gt;0" scale="0.000000" /><attribute name="calibbias" filename="in_accel_x_calibbias" /><attribute name="raw" filename="in_accel_x_raw" /><attribute name="scale" filename="in_accel_scale" /></channel><channel id="accel_y" type="input" ><scan-element index="4" format="be:S32/32&gt;&gt;0" scale="0.000000" /><attribute name="calibbias" filename="in_accel_y_calibbias" /><attribute name="raw" filename="in_accel_y_raw" /><attribute name="scale" filename="in_accel_scale" /></channel><channel id="accel_z" type="input" ><scan-element index="5" format="be:S32/32&gt;&gt;0" scale="0.000000" /><attribute name="calibbias" filename="in_accel_z_calibbias" /><attribute name="raw" filename="in_accel_z_raw" /><attribute name="scale" filename="in_accel_scale" /></channel><channel id="temp0" type="input" ><scan-element index="6" format="be:S16/16&gt;&gt;0" scale="100.000000" /><attribute name="raw" filename="in_temp0_raw" /><attribute name="scale" filename="in_temp0_scale" /></channel><channel id="deltaangl_x" type="input" ><scan-element index="7" format="be:S32/32&gt;&gt;0" scale="0.000000" /><attribute name="raw" filename="in_deltaangl_x_raw" /><attribute name="scale" filename="in_deltaangl_scale" /></channel><channel id="deltaangl_y" type="input" ><scan-element index="8" format="be:S32/32&gt;&gt;0" scale="0.000000" /><attribute name="raw" filename="in_deltaangl_y_raw" /><attribute name="scale" filename="in_deltaangl_scale" /></channel><channel id="deltaangl_z" type="input" ><scan-element index="9" format="be:S32/32&gt;&gt;0" scale="0.000000" /><attribute name="raw" filename="in_deltaangl_z_raw" /><attribute name="scale" filename="in_deltaangl_scale" /></channel><channel id="deltavelocity_x" type="input" ><scan-element index="10" format="be:S32/32&gt;&gt;0" scale="0.000000" /><attribute name="raw" filename="in_deltavelocity_x_raw" /><attribute name="scale" filename="in_deltavelocity_scale" /></channel><channel id="deltavelocity_y" type="input" ><scan-element index="11" format="be:S32/32&gt;&gt;0" scale="0.000000" /><attribute name="raw" filename="in_deltavelocity_y_raw" /><attribute name="scale" filename="in_deltavelocity_scale" /></channel><channel id="deltavelocity_z" type="input" ><scan-element index="12" format="be:S32/32&gt;&gt;0" scale="0.000000" /><attribute name="raw" filename="in_deltavelocity_z_raw" /><attribute name="scale" filename="in_deltavelocity_scale" /></channel><channel id="timestamp" type="input" ><scan-element index="13" format="le:S64/64&gt;&gt;0" /></channel><attribute name="current_timestamp_clock" /><attribute name="filter_low_pass_3db_frequency" /><attribute name="sampling_frequency" /><attribute name="waiting_for_supplier" /><buffer-attribute name="data_available" /><buffer-attribute name="direction" /><debug-attribute name="firmware_date" /><debug-attribute name="firmware_revision" /><debug-attribute name="flash_count" /><debug-attribute name="product_id" /><debug-attribute name="serial_number" /><debug-attribute name="direct_reg_access" /></device><device id="trigger0" name="adis16505-2-dev0" ></device></context>
